# -*- coding: utf-8 -*-
"""
萬能科技大學 11501 創意行銷企劃實務 - 18 週單元大綱與主題配置表 (tools/week_configs.py)
對標：曾光華《行銷企劃：邏輯、創意、執行力》(2026 第五版) ✕ Agentic AI 智慧代理人 ✕ Vibe Coding 操作手冊 ✕ IPAS 證照鑑定
班級：進企管四系3甲 (週一 10~11 節 16:20~17:50) ｜ 教室：F401 教室 ｜ 授課教師：邱俊維 博士
"""

def get_week_configs():
    return [
        {
            'week': 1,
            'module': '基礎學理與導覽模組',
            'title': '課程破冰導覽與行銷企劃新視野',
            'subtitle': '行銷企劃本質 ✕ Agentic AI 協同革命 ✕ Vibe Coding 啟蒙',
            'chapter': '曾光華 CH01 行銷企劃的本質 (Part 1)',
            'agent': 'Agent 1：市場情資洞察 Agent',
            'vibe': 'Hero 視覺區塊 ✕ 品牌調性',
            'ipas': '品牌策略思維與市場環境洞察',
            'core_concept': '企劃三要素：邏輯、創意、執行力',
            'case_name': '傳統中小企業 vs 數位轉型品牌',
            'pitfall': '空有文案點子卻缺乏商業閉環',
            'scamper_q': '替代 (Substitute)：以燕麥奶替代全脂奶'
        },
        {
            'week': 2,
            'module': '基礎學理與導覽模組',
            'title': '企劃三位一體與十步標準程序',
            'subtitle': '企劃程序骨幹 ✕ 邏輯推導架構 ✕ 資料支撐標準',
            'chapter': '曾光華 CH01 行銷企劃的本質 (Part 2)',
            'agent': 'Agent 1：市場情資洞察 Agent',
            'vibe': '一頁式標準 5 大區塊搭建',
            'ipas': '行銷企劃標準流程與資料蒐集',
            'core_concept': '十步企劃程序：問題至效益評估',
            'case_name': '春水堂珍珠奶茶全通路企劃案',
            'pitfall': '跳過問題界定直接做促銷活動',
            'scamper_q': '結合 (Combine)：手搖飲品結合文創體驗'
        },
        {
            'week': 3,
            'module': '基礎學理與導覽模組',
            'title': '企劃願景、使命與 SMART 目標設定',
            'subtitle': '目標層級化 ✕ SMART 檢定 ✕ 效益量化拆解',
            'chapter': '曾光華 CH02 行銷企劃目標',
            'agent': 'Agent 2：STP 市場定位 Agent',
            'vibe': 'Hero 區塊大標題與 CTA 按鈕',
            'ipas': '行銷目標訂定與量化 KPI 評估',
            'core_concept': 'SMART 目標：具體可衡量與時限',
            'case_name': '路易莎咖啡在地生活門市轉型',
            'pitfall': '設定「提升知名度」等模糊空泛目標',
            'scamper_q': '調適 (Adapt)：將精品咖啡融入超商取貨'
        },
        {
            'week': 4,
            'module': '環境洞察與戰略模組',
            'title': '外部宏觀環境 PESTEL 趨勢洞察',
            'subtitle': '大趨勢識別 ✕ 總體環境掃描 ✕ 機會威脅提煉',
            'chapter': '曾光華 CH03 外部環境分析 (Part 1)',
            'agent': 'Agent 1：市場情資洞察 Agent',
            'vibe': 'PESTEL 6 欄響應式網格卡片組件',
            'ipas': 'PESTEL 宏觀大環境趨勢分析',
            'core_concept': 'PESTEL 六大構面與產業機會',
            'case_name': '高齡化少子化浪潮下銀髮健康商機',
            'pitfall': '把短期偶發新聞當成長期大趨勢',
            'scamper_q': '修改 (Modify)：調整包裝規格適應小家庭'
        },
        {
            'week': 5,
            'module': '環境洞察與戰略模組',
            'title': '產業競爭與五力分析模型實戰',
            'subtitle': '波特五力架構 ✕ 競品優劣矩陣 ✕ 關鍵成功因素',
            'chapter': '曾光華 CH03 外部環境分析 (Part 2)',
            'agent': 'Agent 1：市場情資洞察 Agent',
            'vibe': '3 欄式競品對比卡片網頁組件',
            'ipas': '波特五力分析與競爭者矩陣',
            'core_concept': '五力競爭強度與產業獲利空間',
            'case_name': '全聯福利中心跨足生鮮之競爭突圍',
            'pitfall': '只看直接對手忽視跨界替代品威脅',
            'scamper_q': '其他用途 (Put to use)：空瓶轉為環保盆栽'
        },
        {
            'week': 6,
            'module': '環境洞察與戰略模組',
            'title': '企業內部資源能力與 VRIO 分析',
            'subtitle': '資源盤點 ✕ VRIO 護城河檢驗 ✕ 核心能力提煉',
            'chapter': '曾光華 CH04 內部環境分析 (Part 1)',
            'agent': 'Agent 2：STP 市場定位 Agent',
            'vibe': '核心價值主張 (Value Proposition) 卡片',
            'ipas': 'VRIO 分析與企業核心能力檢定',
            'core_concept': 'VRIO 四檢定：價值稀有難模仿組織',
            'case_name': '台積電晶圓代工卓越製造生態系',
            'pitfall': '把人人都有的設備當成核心競爭力',
            'scamper_q': '消除 (Eliminate)：移除多餘繁瑣包裝耗材'
        },
        {
            'week': 7,
            'module': '環境洞察與戰略模組',
            'title': 'SWOT 交叉戰略矩陣與 TOWS 策略',
            'subtitle': '打破清單流 ✕ TOWS 交叉攻防 ✕ 策略優先級',
            'chapter': '曾光華 CH04 內部環境分析 (Part 2)',
            'agent': 'Agent 3：受眾 Persona 畫像 Agent',
            'vibe': '互動式 SWOT 九宮格點擊展開模組',
            'ipas': 'SWOT 與 TOWS 交叉矩陣整合策略',
            'core_concept': 'TOWS 四策略：SO攻/ST抗/WO轉/WT防',
            'case_name': 'Gogoro 智慧雙輪換電生態系戰略',
            'pitfall': '內外不分：把外部機會寫在內部優勢',
            'scamper_q': '倒轉 (Reverse)：顛覆賣車思維改賣里程'
        },
        {
            'week': 8,
            'module': '創意突破與期中審查',
            'title': '激發行銷企劃創意與 SCAMPER 發想',
            'subtitle': '水平思考法 ✕ 奔馳 7 步發散 ✕ 荒謬聯想收斂',
            'chapter': '曾光華 CH05 激發行銷企劃創意',
            'agent': 'Agent 4：SCAMPER 創意奔馳 Agent',
            'vibe': '課堂靈感抽卡機與便利貼倒數計時',
            'ipas': '創新思維與行銷創意工具應用',
            'core_concept': 'SCAMPER 七步法：代/併/調/改/用/除/反',
            'case_name': '宜家家居 IKEA 肉丸與家具複合策展',
            'pitfall': '創意天馬行空卻脫離商業變現邏輯',
            'scamper_q': '奔馳整合：全案 7 步驟循環創新發想'
        },
        {
            'week': 9,
            'module': '創意突破與期中考試',
            'title': '【期中週】期中考試 (筆試/實務測驗)',
            'subtitle': '觀念筆試 ✕ 實務案例題型 ✕ 前半學期學習成效總檢定',
            'chapter': '期中考試範圍：曾光華 CH01 ~ CH05 全冊重點',
            'agent': '期中測驗模組：核心觀念檢定與實務案例分析',
            'vibe': '期中數位測驗系統與即時題型解析',
            'ipas': '期中 40 題專業行銷觀念與企劃邏輯實戰測驗',
            'core_concept': '期中實力檢驗：企劃邏輯、環境洞察與創意發想',
            'case_name': '期中考試實務個案分析與觀念題解',
            'pitfall': '觀念死記硬背、缺乏實務情境推導能力',
            'scamper_q': '期中測驗：筆試作答與企劃實務個案綜合測驗'
        },
        {
            'week': 10,
            'module': '行銷組合與實務模組',
            'title': '新產品上市企劃：概念測試與受眾 Persona',
            'subtitle': '新品失敗率剖析 ✕ 概念測試 ✕ 受眾精準畫像',
            'chapter': '曾光華 CH06 新產品上市 (Part 1)',
            'agent': 'Agent 3：受眾 Persona 畫像 Agent',
            'vibe': '新產品線上早鳥預購一頁式網頁',
            'ipas': '新產品上市定位與目標市場細分',
            'core_concept': '概念測試 (Concept Testing) 四步驟',
            'case_name': 'Dyson 吸塵器與吹風機破壞式創新上市',
            'pitfall': '未經概念測試便投入重金量產上市',
            'scamper_q': '替代材質：採用生物可分解環保原料'
        },
        {
            'week': 11,
            'module': '行銷組合與實務模組',
            'title': '新產品上市發表節奏與三階段排程',
            'subtitle': '上市時程規劃 ✕ 甘特圖控制 ✕ 48小時引爆',
            'chapter': '曾光華 CH06 新產品上市 (Part 2)',
            'agent': 'Agent 5：爆款文案與短影音 Agent',
            'vibe': '倒數計時器 (Countdown) 與限量標籤',
            'ipas': '行銷企劃時程排定與甘特圖控制',
            'core_concept': '上市三階段：預熱暖身/爆發/長尾',
            'case_name': 'Apple 蘋果秋季發表會上市節奏控管',
            'pitfall': '預熱不足開賣當天無人知曉冷場',
            'scamper_q': '調整時程：提前 1 個月啟動封閉公測'
        },
        {
            'week': 12,
            'module': '行銷組合與實務模組',
            'title': '公關策展與事件行銷議題操作',
            'subtitle': '新聞點製造五法 ✕ 快閃活動 ✕ 社群聲量擴散',
            'chapter': '曾光華 CH07 公關與事件行銷 (Part 1)',
            'agent': 'Agent 6：公關活動與策展 Agent',
            'vibe': '快閃活動報名表單與時間軸組件',
            'ipas': '整合行銷傳播 IMC 與公關事件操作',
            'core_concept': '事件行銷五要素：驚喜話題名流共鳴',
            'case_name': '紅牛 Red Bull 太空極限跳傘事件行銷',
            'pitfall': '活動熱鬧落幕卻無人記得主辦品牌',
            'scamper_q': '結合異業：咖啡品牌與潮流服飾快閃'
        },
        {
            'week': 13,
            'module': '行銷組合與實務模組',
            'title': '品牌危機公關處理與黃金 24 小時 SOP',
            'subtitle': '黃金 3 小時止血 ✕ 道歉四原則 ✕ 答客問 Q&A',
            'chapter': '曾光華 CH07 公關與事件行銷 (Part 2)',
            'agent': 'Agent 6：公關活動與策展 Agent',
            'vibe': '常見問答 (FAQ) 折疊手風琴組件',
            'ipas': '品牌形象維護與危機公關處理標準',
            'core_concept': '危機處理四原則：真誠客觀改善補償',
            'case_name': '鼎泰豐面對食安疑慮之透明應對示範',
            'pitfall': '第一時間推託卸責引發公眾怒火炎上',
            'scamper_q': '逆轉劣勢：將產品瑕疵化為品管透明教材'
        },
        {
            'week': 14,
            'module': '行銷組合與實務模組',
            'title': '促銷策略、誘因工具與促銷 ROI 損益試算',
            'subtitle': '價格促銷副作用 ✕ 促銷工具箱 ✕ 損益平衡試算',
            'chapter': '曾光華 CH08 促銷企劃案',
            'agent': 'Agent 7：促銷活動與 ROI 試算 Agent',
            'vibe': '折價券領取彈窗與滿額免運進度條',
            'ipas': '促銷工具設計與促銷 ROI 損益試算',
            'core_concept': '損益平衡點 (BEP) 與促銷邊際貢獻',
            'case_name': '雙十一購物節促銷套路與獲利拆解',
            'pitfall': '只顧營業額衝高卻導致虧本大拍賣',
            'scamper_q': '非價格誘因：以專屬贈品替代直接打折'
        },
        {
            'week': 15,
            'module': '行銷組合與實務模組',
            'title': '全通路 OMO 與多元行銷企劃案例深度剖析',
            'subtitle': '虛實融合 OMO ✕ 綠色 ESG 行銷 ✕ 文創地方創生',
            'chapter': '曾光華 CH09 其他類行銷企劃：案例與分析',
            'agent': 'Agent 7：MarTech 顧客旅程 Agent',
            'vibe': 'LINE 官方帳號導流與多連結導航頁',
            'ipas': '全通路行銷 (OMO) 與數位轉型實務',
            'core_concept': '顧客旅程地圖 (CJM) 與關鍵接觸點',
            'case_name': '誠品生活虛實融合會員經濟生態圈',
            'pitfall': '線上線下價格打架、門市搶業績衝突',
            'scamper_q': '綠色再造：導入循環包裝與減碳抵換'
        },
        {
            'week': 16,
            'module': '整合撰寫與發表模組',
            'title': '專業企劃書黃金十大章節撰寫與排版',
            'subtitle': '十大章節骨架 ✕ 一頁式摘要撰寫 ✕ 視覺排版美學',
            'chapter': '曾光華 CH10 企劃的撰寫與簡報 (Part 1)',
            'agent': 'Agent 8：企劃全案架構一鍵生成 Agent',
            'vibe': '個人行銷企劃全案單頁展示官網',
            'ipas': '企劃書標準架構十步驟與排版指引',
            'core_concept': '黃金一頁式執行摘要 (Executive Summary)',
            'case_name': '麥肯錫顧問報告一頁式摘要標準尺規',
            'pitfall': '企劃書過於冗長無重點、字體混亂失焦',
            'scamper_q': '精簡聚焦：將 50 頁企劃濃縮為黃金一頁紙'
        },
        {
            'week': 17,
            'module': '整合撰寫與發表模組',
            'title': '簡報台風與 3 分鐘 Pitch 閃電發表演練',
            'subtitle': '電梯簡報術 ✕ 評審提問攻防 ✕ 投影片設計原則',
            'chapter': '曾光華 CH10 企劃的撰寫與簡報 (Part 2)',
            'agent': 'Agent 8：企劃全案架構一鍵生成 Agent',
            'vibe': '個人成果作品集首頁 (Portfolio)',
            'ipas': '口頭簡報台風控制與評審應答技巧',
            'core_concept': '3 分鐘電梯簡報結構：痛點方案效益',
            'case_name': '喬布斯 Jobs 蘋果發表會傳奇台風解析',
            'pitfall': '照著投影片逐字朗讀、缺乏眼神交流',
            'scamper_q': '開場鉤子：用一個震撼數字引導全場關注'
        },
        {
            'week': 18,
            'module': '整合實務與期末考試',
            'title': '【期末週】期末考試 (筆試/實務測驗) 與學期總結',
            'subtitle': '綜合筆試 ✕ 行銷企劃實務測驗 ✕ 學期總成績核算結算',
            'chapter': '期末考試範圍：曾光華 CH01 ~ CH10 全書精華',
            'agent': '期末測驗模組：綜合企劃實力評量與成果總結',
            'vibe': '期末數位測驗系統與學期成績回饋',
            'ipas': '180 題 IPAS 證照全域綜合實戰認證',
            'core_concept': '全學期企劃實務整合能力綜合驗收',
            'case_name': '期末考試商業全案實務綜合題解',
            'pitfall': '前後章節觀念脫節、無法融會貫通商業閉環',
            'scamper_q': '期末測驗：全書精華筆試與實務個案綜合測驗'
        }
    ]
